In [1]:
import init
init.init(force_download=False)
import sourcedefender
init.endpoint="http://localhost:5000/rlxmooc"
init.endpoint='https://m5knaekxo6.execute-api.us-west-2.amazonaws.com/dev-v0001/rlxmooc'
init.get_weblink()

Installing sourcedefender...
endpoint https://m5knaekxo6.execute-api.us-west-2.amazonaws.com/dev-v0001/rlxmooc


In [2]:
from local.lib.rlxmoocapi import submit, session
import inspect
student = session.Session(init.endpoint).login( course_id=init.course_id, 
                                                session_id="UDEA", 
                                                lab_id="lab_01" )

ModuleNotFoundError: No module named 'local.lib.rlxmoocapi'

In [7]:
import numpy as np

## Ejercicio 1: Obtener el máximo y el mínimo de una lista

Una de las estructuras de datos en python son las listas, y aprender a obtener datos de ellas es importante para el manejo del lenguaje, por esto vamos a hallar el **max** y el **min** de una de ellas

Ejemplo:
    [1, 7, 11, 3, 5, 2]
    
    el minimo valor es 1
    el valor maximo es 11
    

In [8]:
lst = np.random.randint(50, size=20)
lst

array([33, 44, 32,  3, 17, 22,  1, 48, 43, 31, 10, 42,  4,  6, 11, 13, 48,
       40, 44, 48])

**Tu solución**

Debes de asignar a las variables max y min el valor del maximo y minimo valor en la lista list

In [9]:
maximum = np.max(lst)
minimum = np.min(lst)

In [10]:
## TEACHER
np.max(list), np.min(lst)

(list, 1)

In [11]:
## TEACHER DEFINEGRADER
def grader_00(functions, variables, caller_userid):
    import numpy as np
    
    st_list = variables['lst']
    st_max = variables['maximum']
    st_min = variables['minimum']
    
    t_max = np.max(st_list)
    t_min = np.min(st_list)
    
    if (t_max==st_max) & (t_min==st_min):
        return 5, '<b>correct</b>'
    else:
        return 0, '<b>incorrect</b>'
    
source_functions_names_00 = []
source_variables_names_00 = ['lst', 'maximum', 'minimum']

In [12]:
## TEACHER
teacher = session.Session(init.endpoint).login('test_teacher', 'hola')

In [13]:
## TEACHER SETGRADER
teacher.set_grader(init.course_id, "lab_01", 'task_00',
                  inspect.getsource(grader_00), 'grader_00',
                  source_functions_names_00, source_variables_names_00)

**Registra tu solución en linea**

In [14]:
student.submit_task(namespace=globals(), course_id=init.course_id, lab_id='lab_01', task_id='task_00')

{'grade': 5,
 'message': '<b>correct</b>',
 'submission_stamp': 'UufuuxytcyNXvbObl0Bhyj/5pQ3khWp1KFqneu+7PIoXCFZ0M2A2MRnAMTXtcg1rFVxB09UqfmHEfHyyuvfW0XMOqOKG+WCGJOG9EsN/6xwfd/V1j1Ko9wVZd02jWubT'}

## Ejercicio 2: Crear una función que encuentre la media y desviación estandar

Ejemplo:
    [1, 7, 11, 3, 5, 2]
    
    la media es 4.8
    la desviación estandar es 3.4

In [15]:
def list_mean(lst):
    ## your code here ##
    mean = np.mean(lst)
    return mean

In [16]:
def list_stdev(lst):
    ## your code here ##
    stdev = np.std(lst)
    return stdev

Prueba tus funciones

In [17]:
lst_1 = np.random.randint(10, size=5)
print(lst_1)
print(list_mean(lst_1))
print(list_stdev(lst_1))

[0 6 6 9 0]
4.2
3.6


In [18]:
## TEACHER
np.mean(lst_1), np.std(lst_1)

(4.2, 3.6)

In [19]:
## TEACHER DEFINEGRADER
def grader_01(functions, variables, caller_userid):
    import numpy as np
    
    print('Grader_01')
    
    # retrieve definitions
    namespace = locals()
    for f in functions.values():
        exec(f, namespace)

    st_mean_funct = namespace['list_mean']
    st_stdev_funct = namespace['list_stdev']
    
    error = False
    msg = ''
    
    for i in range(100):
        size = np.random.randint(20)+3
        list = np.random.randint(10, size=size)
        mean = np.mean(list)
        stdev = np.std(list)
        if not (mean==st_mean_funct(list)):
            msg += "input\nlist = \n%s\n"%(str(list))
            msg += "expected output:%s\n"%str(mean)
            msg += "output obtained:%s\n"%str(st_mean_funct(list))
            error = True
            break
        if not (stdev==st_stdev_funct(list)):
            msg += "input\nlist = \n%s\n"%(str(list))
            msg += "expected output:%s\n"%str(stdev)
            msg += "output obtained:%s\n"%str(st_stdev_funct(list))
            error = True
            break
    
    if not error:
        msg += u'<b>CORRECT</b>'
        return 5, '<b>correct</b>'
    else:
        msg += u'<b><font color="red">INCORRECT</font></b>'
        return 0, msg
    
source_functions_names_01 = ['list_mean', 'list_stdev']
source_variables_names_01 = []

In [20]:
## TEACHER
teacher = session.Session(init.endpoint).login('test_teacher', 'hola')

In [21]:
## TEACHER
r = teacher.run_grader_locally("grader_01", source_functions_names_01, source_variables_names_01, locals())
from IPython.display import HTML
print ("grade", r[0])
HTML(r[1])

Grader_01
grade 5


In [22]:
## TEACHER SETGRADER
teacher.set_grader(init.course_id, "lab_01", 'task_01',
                  inspect.getsource(grader_01), 'grader_01',
                  source_functions_names_01, source_variables_names_01)

**Registra tu solución en linea**

In [23]:
student.submit_task(namespace=globals(), course_id=init.course_id, lab_id='lab_01', task_id='task_01')

{'grade': 5,
 'message': '<b>correct</b>',
 'submission_stamp': '3Z3XfG+2BY9Ji3mL1Ya+QPpTdZg5sEPyy3R8kwdEjjXvxhn30mBYTNBXaH3m4bQXFncSNzERP1DC9wkM3VzsdepAx04mvA8LTi6YDhdl2UyZyYP7+Ms8+scLzUpBRzKW'}

## Ejercicio 3: Ordenar una lista

La idea en este ejercicio es que se ordene en forma ascendente los elementos de una lista

Ejemplo:

[1, 7, 11, 3, 5, 2] ---> [1, 2, 3, 5, 7, 11]

In [24]:
def list_sort(list):
    ## your code here ##
    sorted_list = np.sort(list).tolist()
    return sorted_list

Prueba tu función

In [25]:
import random
list = random.sample(range(20), 10)
print(list)
print(list_sort(list))

[18, 5, 7, 10, 17, 3, 6, 13, 2, 0]
[0, 2, 3, 5, 6, 7, 10, 13, 17, 18]


In [26]:
## TEACHER
sorted_list = np.sort(list)
print(sorted_list)

[ 0  2  3  5  6  7 10 13 17 18]


In [27]:
## TEACHER DEFINEGRADER
def grader_02(functions, variables, caller_userid):
    import numpy as np
    import random
    
    print('Grader 02')
    
    # retrieve definitions
    namespace = locals()
    for f in functions.values():
        exec(f, namespace)

    st_sort_funct = namespace['list_sort']
    
    error = False
    msg = ''
    
    for i in range(100):
        size = np.random.randint(15)+3
        list = random.sample(range(size+5), size)
        sorted_list = np.sort(list)
        st_sorted_list = st_sort_funct(list)
        j = 0
        while j < len(st_sorted_list): 
            if(st_sorted_list[j] < st_sorted_list[j - 1]):
                msg += "input\nlist = \n%s\n"%(str(list))
                msg += "expected output:%s\n"%str(sorted_list)
                msg += "output obtained:%s\n"%str(st_sort_funct(list))
                error = True
                break
            j += 1
            
    
    if not error:
        msg += u'<b><font color="red">INCORRECT</font></b>'
        return 0, msg
    else:
        msg += u'<b>CORRECT</b>'
        return 5, '<b>correct</b>'
    
source_functions_names_02 = ['list_sort']
source_variables_names_02 = []

In [28]:
## TEACHER
teacher = session.Session(init.endpoint).login('test_teacher', 'hola')

In [29]:
## TEACHER
r = teacher.run_grader_locally("grader_02", source_functions_names_02, source_variables_names_02, locals())
from IPython.display import HTML
print ("grade", r[0])
HTML(r[1])

Grader 02
grade 5


In [30]:
## TEACHER SETGRADER
teacher.set_grader(init.course_id, 'lab_01', 'task_02',
                  inspect.getsource(grader_02), 'grader_02',
                  source_functions_names_02, source_variables_names_02)

**Registra tu solución en linea**

In [31]:
student.submit_task(namespace=globals(), course_id=init.course_id, lab_id='lab_01', task_id='task_02')

{'grade': 5,
 'message': '<b>correct</b>',
 'submission_stamp': 'MBCU9fd0Lnm3pikkHj/HjbX43xGrarBaki4eMXevPMcef+FaOAlSr7jqj0KuheWCpZ8mAgp/+ubOc6zgJgCQBU0EU2a6m1HG/rnVhz+WtumXSdc15589Iwtc+S6imxWl'}